artigos/urls.py
from django.urls import path
from . import views  # Importamos views para poder usar as suas funções

app_name = 'artigos'

urlpatterns = [

    path('artigos/<int:article_id>/', views.article_detail_view, name='article-detail'),
    path('comentarios/<int:comment_id>/', views.comment_detail_view, name='comment-detail'),
    path('avaliacoes/<int:rating_id>/', views.rating_detail_view, name='rating-detail'),
    path('artigos/', views.articles_list_view, name='index'),
    path('autores/', views.authors_list_view, name='author-list'),
    path('authors/<int:author_id>/', views.author_detail_view, name='author-detail'),


 ]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('index/', views.index_view, name = 'index'),
    path('banda/<int:banda_id>/',views.banda_view, name = 'banda'),
    path('album/<int:album_id>/',views.album_view, name = 'album'),
    path('musica/<int:musica_id>/',views.musica_view, name = 'musica'),
    path('apaga_banda/<int:banda_id>/', views.apaga_banda_view, name="apagarBanda"),
    path('edita_album/<int:album_id>/', views.edita_album_view, name="editarAlbum"),
    path('apaga_album/<int:album_id>/', views.apaga_album_view, name="apagarAlbum"),
    path('edita_musica/<int:musica_id>/', views.edita_musica_view, name="editarMusica"),
    path('nova_banda', views.nova_banda_view, name="novaBanda"),
    path('novo_album/<int:banda_id>/', views.novo_album_view, name="novoAlbum"),
    path('nova_musica/<int:album_id>/', views.nova_musica_view, name="novaMusica"),
    path('edita_banda/<int:banda_id>/', views.edita_banda_view, name="editarBanda"),
    path('apaga_musica/<int:musica_id>/', views.apaga_musica_view, name="apagarMusica"),
]

cursos/urls.py
from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'cursos'

urlpatterns = [
    path('index/', views.curso_view, name = 'index'),
    path('disciplinas/<int:disciplina_id>/', views.disciplinas_view, name = 'disciplinas'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name = 'disciplina'),
]

meteo/urls.py
from django.urls import path
from . import views


app_name = "meteo"

urlpatterns = [
    path('api/cidades/', views.api_lista_cidades, name='api_lista_cidades'),
    path('api/previsao/hoje/<int:city_id>/', views.api_previsao_hoje, name='api_previsao_hoje'),
    path('api/previsao/cinco_dias/<int:city_id>/', views.previsao_cinco_dias, name='api_previsao_cinco_dias'),
    path('tempo/hoje/lisboa/', views.tempo_hoje_lisboa, name='tempo_hoje_lisboa'),
    path('cidades/', views.cidades, name='cidades'),
    path('previsao/<int:city_id>/', views.previsao_cinco_dias, name='previsao_cinco_dias'),
    path('tempo/<int:city_id>/', views.tempo_hoje_cidade, name='tempo_hoje_cidade'),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_me/', views.about_me, name='about_me'),
    path('about_website/', views.about_website, name='about_website'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/' , include('pwsite.urls')),
    path('bandas/' , include('bandas.urls')),
    path('cursos/', include('cursos.urls')),
    path('artigos/', include('artigos.urls')),
    path('festivais/', include('festivais.urls')),
    path('autenticacao/',include('autenticacao.urls')),
    path('meteo/',include('meteo.urls')),
    path('',include('portfolio.urls')),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'portfolio/index.html')

def about_me(request):
    return render(request, 'portfolio/about_me.html')

def about_website(request):
    return render(request, 'portfolio/about_website.html')

portfolio/templates/portfolio/about_me.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Me</title>
    <link rel="stylesheet" href="{% static 'portfolio/estiloabout.css' %}">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body class="aboutme">
    <div class="container">
        <header class="header">
            <div class="header-content">
                <img src="/media/portfolio/foto curriculo - Cópia.jpg" width="25%">
                <p>My name is Bernardo Pinheiro and I am 19 years old
                <br>I am currently taking my bachelors degree in Computer Science</p>
            </div>
        </header>
        <main class="main">
            <h2>My Hobbies</h2>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Basketball_Clipart.svg/400px-Basketball_Clipart.svg.png" width="15%">
        <p>I enjoy playing basketball on my free time</p>
        <img src="https://www.freeiconspng.com/thumbs/controller-icon/controller-game-icon-10.png" width="25%">
        <p>I enjoy playing video games on my free time</p>
</main>
        <aside class="aside">
        <h2>Skills</h2>
        <div class="skill">
            <img src="https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/181_Java_logo_logos-512.png" width = "80px">
            <p>Java Programming</p>
            </div>
            <div class="skill">
        <img src="https://cdn.freebiesupply.com/logos/thumbs/2x/kotlin-2-logo.png" width = "120px">
        <p>Kotlin Programming</p>
            </div>
            <div class="skill">
        <img src="https://brandslogos.com/wp-content/uploads/images/large/python-logo.png" width = "60px">
        <p>Python Programming</p>
            </div>
            <div class="skill">
        <img class="img-sql" src="https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png"  width = "90px">
        <p>SQL Database Management</p>
            </div>
            <div class="skill">
        <img src="https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png" width = "80px">
        <p>C Programming</p>
            </div>
        </aside>

        <nav class="nav">
            <h2>Education</h2>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTABcKb6qz-QMOXv6axmWcNnv7peecHG7CT4A&s" width = "80px">
            <p>Bachelor´s Degree in Computer Science</p>
            <p>2022-Present</p>
            <h2>Professional Experience</h2>
            <img src="https://www.caminhar.org/wp-content/uploads/2021/03/logo_Caminhar_2018-3.png" width = "200px">
            <p>Volunteering</p>
            <p>June 2023 - September 2023</p>
        </nav>
        <footer class="footer">
                <div class="skill-footer">
                    <a href="https://www.linkedin.com/in/bernardo-pinheiro-b074a82bb/" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
                    <a href="https://www.instagram.com/bernas1220/" target="_blank"><i class="fa-brands fa-instagram fa-2x"></i></i>
                    <a href="https://github.com/bernardoP12" target="_blank"><i class="fa-brands fa-github fa-2x"></i>
            </div>


        </footer>
    </div>
</body>
</html>

portfolio/templates/portfolio/about_website.html
{% block content %}

    <style>
        body {
            text-align:center;
            font-size: 30px;
        }
    </style>
    <body>
        <p>Django Hands-On</p>
        <p><video width="640" height="360" controls>
        <source src="media/portfolio/video1.mkv" type="video/mp4">
    </video></p>
        <p>Project Presentation</p>
        <p><video width="640" height="360" controls>
        <source src="media/portfolio/video2.mp4" type="video/mp4">
    </video></p>

 </body>

{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'portfolio/layout.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<style>
    body {
    color: white;
    background: url("/media/portfolio/background.jpg") no-repeat center center/cover;
    position: relative; /* Necessário para posicionamento absoluto do dropdown */
    margin: 0;
    padding: 0;
    height: 100vh;
    font-family: 'Oswald', sans-serif;
    }
    i{
    margin-left: 20px;
    margin-top: 20px;
    cursor: pointer;
    }
</style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'portfolio/estilos.css' %}">
</head>
<body>


    <i id="dark-mode" class="fas fa-moon fa-10x" data-mode="OFF"></i>
    <div id="contador" class ="contador"></div>
    <script src="{% static 'portfolio/scripts.js' %}"></script>

    <h1 class="header1">Welcome to My Portfolio!</h1>
    <p class = "p">Here I will show you a little bit about myself</p>
    <p class = "p2">and my works</p>
    <h2 class="header2">Don´t know the time? Here it is</h2>

</body>
</html>
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'portfolio/estilos.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
</head>
<script src="https://kit.fontawesome.com/7a414a4d6e.js" crossorigin="anonymous"></script>
<body class="layout">

    <div class="dropdown">
        <button>Check out more</button>
        <div class="content">
            <a href="{% url 'portfolio:about_me' %}"><p>Sobre</p></a>
            <a href="{% url 'portfolio:about_website' %}"><p>Website</p></a>
            <a href="{% url 'artigos:index' %}"><p>Artigos</p></a>
            <a href="{% url 'bandas:index' %}"><p>Bandas</p></a>
            <a href="{% url 'cursos:index' %}"><p>Cursos</p></a>
            <a href="{% url 'meteo:cidades' %}"><p>Meteorologia</p></a>

        </div>
    </div>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>