bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('index/', views.index_view, name = 'index'),
    path('banda/<int:banda_id>/',views.banda_view, name = 'banda'),
    path('album/<int:album_id>/',views.album_view, name = 'album'),
    path('musica/<int:musica_id>/',views.musica_view, name = 'musica'),
    path('apaga_banda/<int:banda_id>/', views.apaga_banda_view, name="apagarBanda"),
    path('edita_album/<int:album_id>/', views.edita_album_view, name="editarAlbum"),
    path('apaga_album/<int:album_id>/', views.apaga_album_view, name="apagarAlbum"),
    path('edita_musica/<int:musica_id>/', views.edita_musica_view, name="editarMusica"),
    path('nova_banda', views.nova_banda_view, name="novaBanda"),
    path('novo_album/<int:banda_id>/', views.novo_album_view, name="novoAlbum"),
    path('nova_musica/<int:album_id>/', views.nova_musica_view, name="novaMusica"),
    path('edita_banda/<int:banda_id>/', views.edita_banda_view, name="editarBanda"),
    path('apaga_musica/<int:musica_id>/', views.apaga_musica_view, name="apagarMusica"),
]

meteo/urls.py
from django.urls import path
from . import views


app_name = "meteo"

urlpatterns = [
    path('api/cidades/', views.api_lista_cidades, name='api_lista_cidades'),
    path('api/previsao/hoje/<int:city_id>/', views.api_previsao_hoje, name='api_previsao_hoje'),
    path('api/previsao/cinco_dias/<int:city_id>/', views.previsao_cinco_dias, name='api_previsao_cinco_dias'),
    path('tempo/hoje/lisboa/', views.tempo_hoje_lisboa, name='tempo_hoje_lisboa'),
    path('cidades/', views.cidades, name='cidades'),
    path('previsao/<int:city_id>/', views.previsao_cinco_dias, name='previsao_cinco_dias'),
    path('tempo/<int:city_id>/', views.tempo_hoje_cidade, name='tempo_hoje_cidade'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/' , include('pwsite.urls')),
    path('bandas/' , include('bandas.urls')),
    path('cursos/', include('cursos.urls')),
    path('artigos/', include('artigos.urls')),
    path('festivais/', include('festivais.urls')),
    path('autenticacao/',include('autenticacao.urls')),
    path('meteo/',include('meteo.urls')),
    path('',include('portfolio.urls')),
]

bandas/models.py
from django.db import models

class Banda(models.Model):
    nome = models.CharField(max_length=100)
    nacionalidade = models.CharField(max_length=100, null=True)
    ano = models.IntegerField()
    genero = models.CharField(max_length=50)
    foto = models.ImageField(upload_to='fotos_bandas/')

    def __str__(self):
        return f'{self.nome}'

class Album(models.Model):
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE, null=True)
    titulo = models.CharField(max_length=100)
    ano = models.IntegerField()
    capa = models.ImageField(upload_to='capas_albuns/')

    def __str__(self):
        return f'{self.titulo} - {self.banda.nome}'

class Musica(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    duracao = models.CharField(max_length=100)
    spotify_link = models.URLField(blank=True)
    letra = models.TextField(default='', null=True, blank=True)
    biografia = models.TextField(default='', null=True, blank=True)

    def __str__(self):
        return f'{self.titulo} - {self.duracao} - {self.album.banda.nome}'

bandas/forms.py
from django import forms
from .models import Banda, Album, Musica
from django.contrib.auth.models import User

class UserRegistrationFrom(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username','first_name','last_name','email','password']

    widgets = {'password':forms.PasswordInput}


class AlbumForm(forms.ModelForm):
  capa = forms.ImageField(required=False)
  class Meta:
    model = Album
    fields = '__all__'
    help_texts = {
            'banda': 'Nome da banda.',
            'titulo': 'Titulo do album.',
            'ano': 'Ano de lancamento.',
            'capa': 'Fotografia da capa do album.',
        }

class BandaForm(forms.ModelForm):
    foto = forms.ImageField(required=False)
    class Meta:
        model = Banda
        fields = '__all__'

        help_texts = {
            'nome': 'Nome da banda.',
            'nacionalidade': 'Nacionalidade da banda.',
            'genero': 'Genero musical da banda.',
            'ano': 'Ano de criacao da banda.',
            'foto': 'Fotografia da banda.',
        }

class MusicaForm(forms.ModelForm):
  class Meta:
    model = Musica
    fields = '__all__'
    help_texts = {
            'album': 'Nome do album.',
            'titulo': 'Titulo da música.',
            'duracao': 'Duracao.',
            'spotify_link': 'Link do spotify.',
            'letra': 'Letra da música.',
            'biografia': 'Biografia (4-5 linhas).',
        }

bandas/views.py
from django.shortcuts import render, redirect
from .models import Banda, Album, Musica
from django.contrib.auth.decorators import login_required
from .forms import BandaForm, AlbumForm, MusicaForm

# Create your views here.

def index_view(request):
    context = {
        'bandas': Banda.objects.all().order_by('nome'),
        'bandas_rock' : Banda.objects.filter(genero__contains='Rock'),
        'bandas_metal' : Banda.objects.filter(genero__contains='Metal'),
        'bandas_grunge' : Banda.objects.filter(genero__contains='Grunge')

    }
    return render(request,'bandas/index.html',context)


def banda_view(request, banda_id):
    context = {
        'banda': Banda.objects.get(id=banda_id),
        'albuns': Album.objects.filter(banda = banda_id).order_by('titulo'),
    }

    return render(request,'bandas/banda.html',context)

def album_view(request,album_id):
    context = {
        'album': Album.objects.get(id=album_id),
        'musicas': Musica.objects.filter(album = album_id).order_by('titulo')
    }

    return render(request,'bandas/album.html',context)

def musica_view(request,musica_id):
    context = {
        'musica': Musica.objects.get(id=musica_id),
    }
    return render(request,'bandas/musica.html',context)


@login_required
def nova_banda_view(request):
    form = BandaForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('bandas:index')

    context = {'form': form}
    return render(request, 'bandas/novaBanda.html', context)


@login_required
def edita_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)

    if request.POST:
        form = BandaForm(request.POST or None, request.FILES, instance=banda)
        if form.is_valid():
            form.save()
            return redirect('bandas:index')
    else:
        form = BandaForm(instance=banda)

    context = {'form': form, 'banda':banda}
    return render(request, 'bandas/editarBanda.html', context)

@login_required
def apaga_banda_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    banda.delete()
    return redirect('bandas:index')

@login_required
def edita_album_view(request, album_id):
    album = Album.objects.get(id=album_id)

    if request.POST:
        form = AlbumForm(request.POST or None, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bandas:index')
    else:
        form = AlbumForm(instance=album)

    context = {'form': form, 'album':album}
    return render(request, 'bandas/editarAlbum.html', context)


@login_required
def apaga_album_view(request, album_id):
    album = Album.objects.get(id=album_id)
    album.delete()
    return redirect('bandas:index')


@login_required
def novo_album_view(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    form = AlbumForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        album = form.save(commit=False)
        album.banda = banda
        album.save()
        return redirect('bandas:album')

    context = {'form': form}
    return render(request, 'bandas/novoAlbum.html', context)

@login_required
def edita_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)

    if request.POST:
        form = MusicaForm(request.POST or None, request.FILES, instance=musica)
        if form.is_valid():
            form.save()
            return redirect('bandas:index')
    else:
        form = MusicaForm(instance=musica)

    context = {'form': form, 'musica':musica}
    return render(request, 'bandas/editarMusica.html', context)


@login_required
def apaga_musica_view(request, musica_id):
    musica = Musica.objects.get(id=musica_id)
    musica.delete()
    return redirect('bandas:index')


@login_required
def nova_musica_view(request, album_id):
    album = Album.objects.get(id=album_id)
    form = MusicaForm(request.POST or None, request.FILES)

    if form.is_valid():
        musica = form.save(commit=False)
        musica.album = album
        musica.save()
        return redirect('bandas:musica')

    context = {'form': form}
    return render(request, 'bandas/novaMusica.html', context)

bandas/templates/bandas/album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <header>
        <a href="{% url 'bandas:index' %}"><button class="button-menu">Menu</button></a>
    </header>

<body class="album">
    <h2>{{ album.titulo }}</h2>

    {% if album.capa %}
        <p><img src="{{ album.capa.url }}" style="max-width: 30%;"></p>
    {% else %}
        <p>Nenhuma foto inserida</p>
    {% endif %}
    <p>Ano de lançamento: {{ album.ano }}</p>

    <h3>Músicas</h3>

    {% for musica in musicas %}
        <li>
            <a href="{% url 'bandas:musica' musica.id %}">{{ musica.titulo }}, {{ musica.duracao }}</a>
            {% if user.is_authenticated and perms.bandas.change_musica %}
                <a href="{% url 'bandas:editarMusica' musica.id %}"><small><button class="button-edit">Editar</button></small></a>
            {% endif %}
        </li>
    {% endfor %}
    {% if user.is_authenticated and perms.bandas.create_musica %}
        <a href="{% url 'bandas:novaMusica' album.id %}"><button class="button-edit">Nova Música</button></a>
    {% endif %}
{% endblock %}

bandas/templates/bandas/banda.html
{% extends 'bandas/layout.html' %}
{% block content %}

    <header>
        <a href = "{% url 'bandas:index' %}"><button class="button-menu">Menu</button></a>
    </header>
<body class = "banda">

</body>
    <h3>{{ banda }}</h3>

    {% if banda.foto %}
        <p id = "foto"> <img src = '{{banda.foto.url}}' style="max-width: 10%;"></p>
    {% else %}
        <p>Nenhuma foto foi inserida</p>
    {% endif %}

    <p> Nacionalidade: {{ banda.nacionalidade }}</p>
    <p> Ano de criação: {{ banda.ano }}</p>
    <p> Género: {{ banda.genero }}</p>

    <h3>Álbuns</h3>

    {% for album in albuns %}
        <li>
            <a href="{% url 'bandas:album' album.id %}">{{ album.titulo }}, {{ album.ano_lancamento }}</a>
            {% if user.is_authenticated and perms.bandas.change_album %}
            <a href ="{% url 'bandas:editarAlbum' album.id %}"><button class="button-edit">Editar</button></a>
            {% endif %}
        </li>
    {% endfor %}
    {% if user.is_authenticated and perms.bandas.create_album %}
            <a href="{% url 'bandas:novoAlbum' banda.id %}"><button class="button-edit">Novo Album</button></a>
    {% endif %}
{% endblock %}

bandas/templates/bandas/editarAlbum.html
{% extends 'bandas/layout.html' %}

{% block content %}
<body class = "album">
</body>
    <h2>Editar Album</h2>

    <form action="{% url 'bandas:editarAlbum' album.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar">
    </form>

    <a href="{% url 'bandas:index' %}">
      <button class = "button-menu">Voltar atrás</button>
    </a>

    <a href="{% url 'bandas:apagarAlbum' album.id %}">
      <button class = "button-cancel">Apagar</button>
    </a>

{% endblock %}

bandas/templates/bandas/editarBanda.html
{% extends 'bandas/layout.html' %}

{% block content %}
<body class = "banda">
</body>
    <h2>Editar Banda</h2>

    <form action="{% url 'bandas:editarBanda' banda.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar">
    </form>

    <a href="{% url 'bandas:index' %}">
      <button class = "button-menu">Voltar atrás</button>
    </a>

    <a href="{% url 'bandas:apagarBanda' banda.id %}">
      <button class = "button-cancel">Apagar</button>
    </a>

{% endblock %}

bandas/templates/bandas/editarMusica.html
{% extends 'bandas/layout.html' %}

{% block content %}
<body class = "musica">
</body>
    <h2>Editar Musica</h2>

    <form action="{% url 'bandas:editarMusica' musica.id %}" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar">
    </form>

    <a href="{% url 'bandas:index' %}">
      <button class ="button-menu">Voltar atrás</button>
    </a>

    <a href="{% url 'bandas:apagarMusica' musica.id %}">
      <button class = "button-cancel">Apagar</button>
    </a>

{% endblock %}

bandas/templates/bandas/index.html
{% extends 'bandas/layout.html' %}
{% block content %}

    <div class="container">
        <div class="rock">
            <h1>Rock</h1>
    {% for banda in bandas_rock %}


        <p><a href = "{% url 'bandas:banda' banda.id %}"> {{banda.nome}}</a></p>

        {% if banda.foto %}
            <p id = "foto"> <img src = '{{banda.foto.url}}' style="max-width: 40%;"></p>
        {% else %}
            <p>Nenhuma foto disponível</p>
        {% endif %}

        {% if user.is_authenticated and perms.bandas.change_banda %}
            <a href ="{% url 'bandas:editarBanda' banda.id %}"><button class="button-edit">Editar</button></a>
        {% endif %}

        {% if user.is_authenticated and perms.bandas.create_banda %}
        <a href="{% url 'bandas:novaBanda' %}"><button class = "button-edit">Nova Banda</button></a>
        {% endif %}

    {% endfor %}
        </div><!--rock-->

        <div class="metal">
            <h1>Metal</h1>
    {% for banda in bandas_metal %}

        <p><a href = "{% url 'bandas:banda' banda.id %}"> {{banda.nome}}</a></p>

        {% if banda.foto %}
            <p id = "foto"> <img src = '{{banda.foto.url}}' style="max-width: 40%;"></p>
        {% else %}
            <p>Nenhuma foto disponível</p>
        {% endif %}

        {% if user.is_authenticated and perms.bandas.change_banda %}
            <a href ="{% url 'bandas:editarBanda' banda.id %}"><button class="button-edit">Editar</button></a>
        {% endif %}

        {% if user.is_authenticated and perms.bandas.create_banda %}
        <a href="{% url 'bandas:novaBanda' %}"><button class = "button-edit">Nova Banda</button></a>
        {% endif %}

    {% endfor %}
    </div><!--metal-->

    <div class="grunge">
        <h1>Grunge</h1>
    {% for banda in bandas_grunge %}

        <p><a href = "{% url 'bandas:banda' banda.id %}"> {{banda.nome}}</a></p>

        {% if banda.foto %}
            <p id = "foto"> <img src = '{{banda.foto.url}}' style="max-width: 40%;"></p>
        {% else %}
            <p>Nenhuma foto disponível</p>
        {% endif %}

        {% if user.is_authenticated and perms.bandas.change_banda %}
            <a href ="{% url 'bandas:editarBanda' banda.id %}"><button class="button-edit">Editar</button></a>
        {% endif %}

        {% if user.is_authenticated and perms.bandas.create_banda %}
        <a href="{% url 'bandas:novaBanda' %}"><button class = "button-edit">Nova Banda</button></a>
        {% endif %}

    {% endfor %}
    </div><!--grunge-->

    </div> <!--container-->
{% endblock %}

bandas/templates/bandas/layout.html
<html>
    <head>
        <title>Bandas</title>
        <head>
  {% load static %}
  <link rel="stylesheet" href="{% static 'bandas/estilos.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/5d1319edfb.js" crossorigin="anonymous"></script>
    </head>
    </head>
    <body>
        <header>
            <h1>Bandas</h1>
        </header>

        <main>

            {% block content %}
            {% endblock %}

        </main>

        <footer>
            <p>Universidade Lusófona</p>
        </footer>
    </body>
</html>

bandas/templates/bandas/musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <header>
        <a href = "{% url 'bandas:index' %}"><button class="button-menu">Menu</button></a>
    </header>

<body class = "musica"></body>
    <h2>{{ musica.titulo }}</h2>

    <p> <big>Duração</big>: {{ musica.duracao }}</p>
    <p> <big>Spotify_link</big>: {{musica.spotify_link}}</p>

{% endblock %}

bandas/templates/bandas/novaBanda.html
{% extends 'bandas/layout.html' %}

{% block content %}
<body class = "banda" ></body>
    <h2>Nova Banda</h2>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar">
    </form>

{% endblock %}

bandas/templates/bandas/novaMusica.html
{% extends 'bandas/layout.html' %}

{% block content %}
<body class = "musica" ></body>
    <h2>Nova Musica</h2>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar">
    </form>

{% endblock %}

bandas/templates/bandas/novoAlbum.html
{% extends 'bandas/layout.html' %}

{% block content %}
<body class = "album" ></body>
    <h2>Novo Album</h2>

    <form action="" method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Criar">
    </form>

{% endblock %}