cursos/urls.py
from django.urls import path
from . import views  # importamos views para poder usar as suas funções

app_name = 'cursos'

urlpatterns = [
    path('index/', views.curso_view, name = 'index'),
    path('disciplinas/<int:disciplina_id>/', views.disciplinas_view, name = 'disciplinas'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_view, name = 'disciplina'),
]

meteo/urls.py
from django.urls import path
from . import views


app_name = "meteo"

urlpatterns = [
    path('api/cidades/', views.api_lista_cidades, name='api_lista_cidades'),
    path('api/previsao/hoje/<int:city_id>/', views.api_previsao_hoje, name='api_previsao_hoje'),
    path('api/previsao/cinco_dias/<int:city_id>/', views.previsao_cinco_dias, name='api_previsao_cinco_dias'),
    path('tempo/hoje/lisboa/', views.tempo_hoje_lisboa, name='tempo_hoje_lisboa'),
    path('cidades/', views.cidades, name='cidades'),
    path('previsao/<int:city_id>/', views.previsao_cinco_dias, name='previsao_cinco_dias'),
    path('tempo/<int:city_id>/', views.tempo_hoje_cidade, name='tempo_hoje_cidade'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/' , include('pwsite.urls')),
    path('bandas/' , include('bandas.urls')),
    path('cursos/', include('cursos.urls')),
    path('artigos/', include('artigos.urls')),
    path('festivais/', include('festivais.urls')),
    path('autenticacao/',include('autenticacao.urls')),
    path('meteo/',include('meteo.urls')),
    path('',include('portfolio.urls')),
]

cursos/models.py
from django.db import models

class Curso(models.Model):
    apresentacao = models.CharField(max_length=100)
    objetivos = models.CharField(max_length=100)
    competencias = models.CharField(max_length=100)

class AreaCientifica(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=100)

class Docente(models.Model):
    nome = models.CharField(max_length=100)
    departamento = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=15, blank=True, null=True)

class Disciplina(models.Model):
    nome = models.CharField(max_length=100)
    ano = models.IntegerField()
    semestre = models.CharField(max_length=20)
    ects = models.IntegerField()
    curricularUnitReadableCode = models.CharField(max_length=20)
    area_cientifica = models.ForeignKey(AreaCientifica, on_delete=models.CASCADE)
    docentes = models.ManyToManyField(Docente, related_name='disciplinas')

    def __str__(self):
        return f'{self.nome}'

class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length=50)
    versao = models.CharField(max_length=15, blank=True, null=True)

class Projeto(models.Model):
    disciplina = models.OneToOneField(Disciplina, on_delete=models.CASCADE)
    descricao = models.TextField()
    conceitos_aplicados = models.TextField()
    tecnologias_usadas = models.TextField()
    linguagens = models.ManyToManyField(LinguagemProgramacao, related_name='projetos')
    imagem = models.ImageField(upload_to='imagens_projetos/')
    link_video = models.URLField(max_length=200)
    link_github = models.URLField(max_length=200, blank=True, null=True)

cursos/views.py
from django.shortcuts import render
from .models import *

def curso_view(request):
    context = {
        'cursos' : Curso.objects.all(),
    }

    return render (request, 'cursos/index.html', context)

def disciplinas_view(request, disciplina_id):
    context = {

        'disciplinas' : Disciplina.objects.all(),
        'disciplina' : Disciplina.objects.get(id = disciplina_id),
        'ano1' : Disciplina.objects.filter(ano=1),
        'ano2' : Disciplina.objects.filter(ano=2),
        'ano3' : Disciplina.objects.filter(ano=3),
        'semestre1' : Disciplina.objects.filter(semestre ='1º Semestre'),
        'semestre2' : Disciplina.objects.filter(semestre ='2º Semestre'),
    }

    return render(request, 'cursos/disciplinas.html', context)


def disciplina_view(request, disciplina_id):
    context = {

        'disciplina' : Disciplina.objects.get(id = disciplina_id)
    }

    return render(request, 'cursos/disciplina.html', context)

cursos/templates/cursos/disciplina.html
{% load static %}
<title>{{disciplina.nome}}</title>
<h1><header>{{disciplina.nome}}</header></h1>
<link rel="stylesheet" href="{% static 'cursos/estilos.css' %}">
{% block content %}

    <style>
            body {
                background: url('https://thetangerinebowl.com/wp-content/uploads/2014/08/light-wood-BK1.png');
                color:black;
                font-size:30px;
            }
        </style>

    <header>
        <a href = "{% url 'cursos:index' %}"><button class="button-menu">Menu</button></a>
    </header>

    <div class = "disciplina">
    <h3>Detalhes de {{disciplina.nome}} </h3>

    <p>Ano: {{disciplina.ano}}º</p>
    <p>Semestre: {{disciplina.semestre}}</p>
    <p>Ects: {{disciplina.ects}}</p>
    <p>Curricular Unit Readable Code: {{disciplina.curricularUnitReadableCode}}</p>
    <p>Area Ciêntifica: {{disciplina.area_cientifica.nome}}</p>
    </div>
{% endblock %}

cursos/templates/cursos/disciplinas.html
{% load static %}
<head>

    <title>Disciplinas</title>
    <link rel="stylesheet" href="{% static 'cursos/estilos.css' %}">
</head>

    <style>
            body {
                background: url('https://thetangerinebowl.com/wp-content/uploads/2014/08/light-wood-BK1.png');
                color:black;
            }
        </style>

<h1><header>Disciplinas</header></h1>
    <header>
        <a href = "{% url 'cursos:index' %}"><button class="button-menu">Menu</button></a>
    </header>

{% block content %}
    <div class = "container">

    <div class = "1ano">
    <h3> 1º Ano </h3>
    <p>1º Semestre</p>
    {% for disciplina in ano1 %}
    {% if disciplina in semestre1 %}
    <li>
        <a href="{% url 'cursos:disciplina' disciplina.id %}">{{disciplina.nome}}</a>
    </li>
    {% endif %}
    {% endfor %}

    <p>2º Semestre</p>
    {% for disciplina in ano1 %}
    {% if disciplina in semestre2 %}
    <li>
        <a href="{% url 'cursos:disciplina' disciplina.id %}">{{disciplina.nome}}</a>
    </li>
    {% endif %}
    {% endfor %}

    </div>

    <div class = "2ano">
    <h3> 2º Ano </h3>
    <p>1º Semestre</p>
    {% for disciplina in ano2 %}
    {% if disciplina in semestre1 %}
    <li>
        <a href="{% url 'cursos:disciplina' disciplina.id %}">{{disciplina.nome}}</a>
    </li>
    {% endif %}
    {% endfor %}

    <p>2º Semestre</p>
    {% for disciplina in ano2 %}
    {% if disciplina in semestre2 %}
    <li>
        <a href="{% url 'cursos:disciplina' disciplina.id %}">{{disciplina.nome}}</a>
    </li>
    {% endif %}
    {% endfor %}
    </div>

    <div class = "3ano">
    <h3> 3º Ano </h3>
    <p>1º Semestre</p>
    {% for disciplina in ano3 %}
    {% if disciplina in semestre1 %}
    <li>
        <a href="{% url 'cursos:disciplina' disciplina.id %}">{{disciplina.nome}}</a>
    </li>
    {% endif %}
    {% endfor %}

    <p>2º Semestre</p>
    {% for disciplina in ano3 %}
    {% if disciplina in semestre2 %}
    <li>
        <a href="{% url 'cursos:disciplina' disciplina.id %}">{{disciplina.nome}}</a>
    </li>
    {% endif %}
    {% endfor %}
    </div>
    </div>
{% endblock %}

cursos/templates/cursos/index.html
{% extends 'cursos/layout.html' %}

{% block content %}
<h2>Curso de Engenharia Informática</h2>
<ul>
    {% for curso in cursos %}
        <li>
            <h3><a href="{% url 'cursos:disciplinas' curso.id %}">LEI</a></h3>
            <p>{{ curso.apresentacao }}</p>
            <p>{{ curso.objetivos }}</p>
            <p>{{ curso.competencias }}</p>
        </li>
    {% endfor %}
</ul>
{% endblock %}

cursos/templates/cursos/layout.html
<html>
    <head>
        <title>Cursos</title>
        <style>
            body {
                background: url('https://thetangerinebowl.com/wp-content/uploads/2014/08/light-wood-BK1.png');
                color:black;
                font-size:25px;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Cursos</h1>
        </header>

        <main>

            {% block content %}
            {% endblock %}

        </main>

        <footer>
            <p>Universidade Lusófona</p>
        </footer>
    </body>
</html>